# Generated by Django 3.0.6 on 2021-08-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20210808_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='contributor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.IntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
    ]
