# Generated by Django 3.0.6 on 2021-10-08 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_auto_20211008_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='like_users',
            field=models.ManyToManyField(related_name='like_musics', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
