# Generated by Django 3.0.6 on 2021-07-22 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='阅读量')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(verbose_name='最近更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(max_length=200, verbose_name='简介')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover', models.URLField(verbose_name='图片地址')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('like_users', models.ManyToManyField(related_name='articles_like', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
        ),
    ]
