version: "3.8"

services:
  web:
    build: .
    container_name: hinghwa-dict-local
    # 这一步最关键：把当前目录同步到容器，改代码即刻生效
    volumes:
      - .:/usr/src/HinghwaDict-backend
    ports:
      - "8000:8000"
    # 模拟交互式终端，方便看日志
    stdin_open: true
    tty: true
    # 如果有数据库文件，Docker会自动在容器内创建
    environment:
      - PYTHONUNBUFFERED=1