# Generated by Django 3.1 on 2023-03-23 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_users",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="like_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论点赞用户",
            ),
        )
    ]

