# Generated by Django 3.1.14 on 2023-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rewards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="商品名称"),
                ),
                ("point", models.IntegerField(blank=True, verbose_name="所需积分")),
                ("left", models.IntegerField(blank=True, verbose_name="剩余数量")),
                (
                    "picture",
                    models.URLField(
                        blank=True,
                        default="https://cos.edialect.top/website/默认头像.jpg",
                        verbose_name="商品图片",
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, max_length=200, verbose_name="商品详情"),
                ),
            ],
        ),
    ]
