# Generated by Django 3.1.14 on 2023-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=20, verbose_name="称号"),
                ),
                ("point", models.IntegerField(blank=True, verbose_name="所需积分")),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="颜色"),
                ),
                (
                    "owned",
                    models.CharField(blank=True, max_length=10, verbose_name="是否拥有"),
                ),
            ],
        ),
    ]
