# Generated by Django 3.1.14 on 2023-07-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rewards", "0002_auto_20230725_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="id",
            field=models.CharField(
                blank=True,
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "address",
                    models.CharField(blank=True, max_length=100, verbose_name="地址"),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=10, verbose_name="姓名"),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=100, verbose_name="备注"),
                ),
                (
                    "id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
