# Generated by Django 3.0.6 on 2021-07-23 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, verbose_name='生日')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('avatar', models.URLField(default='http://118.25.147.215:8080/image/defaultUser.png', verbose_name='头像')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='县区')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='乡镇')),
            ],
        ),
    ]
