# Generated by Django 3.0.6 on 2022-01-21 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wechat', models.CharField(blank=True, max_length=128, verbose_name='微信标识码')),
                ('qq', models.CharField(blank=True, max_length=128, verbose_name='qq标识码')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, default='1970-1-1', verbose_name='生日')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('avatar', models.URLField(blank=True, default='https://hinghwadict-1259415432.cos.ap-shanghai.myqcloud.com/files/image/1/2022/01/19/bMuzwU97XtBZHve.jpg', verbose_name='头像')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='县区')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='乡镇')),
            ],
            options={
                'verbose_name': '用户详细信息',
                'verbose_name_plural': '用户详细信息',
            },
        ),
    ]
