# Generated by Django 3.0.6 on 2021-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='location_1',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='location_2',
            new_name='town',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
