# Generated by Django 3.0.6 on 2021-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210724_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.URLField(blank=True, default='http://118.25.147.215:8080/image/defaultUser.png', verbose_name='头像'),
        ),
    ]
