# Generated by Django 3.0.6 on 2021-07-23 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20210723_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shengmu', models.CharField(max_length=30, verbose_name='声母')),
                ('IPA', models.CharField(max_length=30, verbose_name='IPA')),
                ('pinyin', models.CharField(max_length=30, verbose_name='拼音')),
                ('yunmu', models.CharField(max_length=30, verbose_name='韵母')),
                ('shengdiao', models.CharField(max_length=10, verbose_name='声调')),
                ('character', models.CharField(max_length=10, verbose_name='汉字')),
                ('county', models.CharField(max_length=100, verbose_name='县区')),
                ('town', models.CharField(max_length=100, verbose_name='乡镇')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60, verbose_name='词')),
                ('definition', models.TextField(verbose_name='注释')),
                ('annotation', models.TextField(verbose_name='附注')),
                ('mandarin', models.TextField(verbose_name='对应普通话解释')),
                ('views', models.IntegerField(default=0, verbose_name='访问量')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribute_words', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('related_articles', models.ManyToManyField(related_name='related_words', to='article.Article', verbose_name='相关帖子')),
                ('related_words', models.ManyToManyField(related_name='_word_related_words_+', to='word.Word', verbose_name='相关词汇')),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(verbose_name='来源')),
                ('ipa', models.CharField(max_length=50, verbose_name='ipa')),
                ('pinyin', models.CharField(max_length=50, verbose_name='拼音')),
                ('county', models.CharField(max_length=100, verbose_name='县区')),
                ('town', models.CharField(max_length=100, verbose_name='乡镇')),
                ('visibility', models.BooleanField(default=False, verbose_name='是否审核')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribute_pronunciation', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation', to='word.Word', verbose_name='词语')),
            ],
        ),
    ]
