# Generated by Django 3.0.6 on 2021-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='IPA',
        ),
        migrations.AddField(
            model_name='character',
            name='ipa',
            field=models.CharField(default='', max_length=30, verbose_name='ipa'),
        ),
    ]
