# Generated by Django 3.0.6 on 2021-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20210731_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation',
            name='views',
            field=models.IntegerField(default=0, verbose_name='访问量'),
        ),
        migrations.AddField(
            model_name='word',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
    ]
