# Generated by Django 3.0.6 on 2021-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20210801_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='mandarin',
            field=models.TextField(verbose_name='对应普通话词语'),
        ),
    ]
