# Generated by Django 3.0.6 on 2021-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210725_0958'),
        ('word', '0004_auto_20210806_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_words', to='article.Article', verbose_name='相关帖子'),
        ),
        migrations.AlterField(
            model_name='word',
            name='related_words',
            field=models.ManyToManyField(blank=True, related_name='_word_related_words_+', to='word.Word', verbose_name='相关词汇'),
        ),
    ]
