# Generated by Django 3.0.6 on 2021-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20210806_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': '单字', 'verbose_name_plural': '单字'},
        ),
        migrations.AlterModelOptions(
            name='pronunciation',
            options={'verbose_name': '语音', 'verbose_name_plural': '语音'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '词语', 'verbose_name_plural': '词语'},
        ),
    ]
