# Generated by Django 3.0.6 on 2021-08-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0006_auto_20210808_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='contributor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contribute_pronunciation', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='word',
            name='contributor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contribute_words', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AlterField(
            model_name='word',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='访问量'),
        ),
    ]
