# Generated by Django 3.1.14 on 2023-07-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userinfo_default_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="color",
            field=models.CharField(
                blank=True, default="#000000", max_length=7, verbose_name="字体颜色"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="points",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="reasons",
            field=models.TextField(blank=True, verbose_name="积分变动原因"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="timestamps",
            field=models.TextField(blank=True, verbose_name="积分变动时间戳"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="title",
            field=models.CharField(blank=True, max_length=50, verbose_name="头衔"),
        ),
    ]
