# Generated by Django 3.1.14 on 2023-07-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_auto_20230718_1037"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="points",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="points_now",
            field=models.IntegerField(default=0, verbose_name="当前积分"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="points_sum",
            field=models.IntegerField(default=0, verbose_name="总积分"),
        ),
    ]
