# Generated by Django 3.1.14 on 2023-07-24 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_auto_20230721_0854"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="reasons",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="timestamps",
        ),
    ]
