# Generated by Django 3.1.14 on 2023-07-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230724_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='title',
        ),
    ]
