# Generated by Django 3.0.6 on 2021-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.TextField(verbose_name='本站公告')),
                ('hot_articles', models.TextField(verbose_name='热门文章')),
                ('word_of_the_day', models.TextField(verbose_name='每日一词')),
                ('carousal', models.TextField(verbose_name='精品推荐')),
            ],
        ),
    ]
