# Generated by Django 3.0.6 on 2021-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': '网页内容', 'verbose_name_plural': '网页内容'},
        ),
        migrations.RenameField(
            model_name='website',
            old_name='carousal',
            new_name='carousel',
        ),
    ]
