# Generated by Django 3.1.14 on 2023-09-16 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0004_word_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"verbose_name": "词单", "verbose_name_plural": "词单"},
        ),
    ]
