name: lint-changed-files
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Lint tests JSON
        run: |
          for i in tests/*; do
            jq . $i > out.tmp && mv out.tmp $i
          done
          git --no-pager diff
          if ! git diff --quiet; then
            echo "Please run 'for i in tests/*; do jq . \$i > out.tmp && mv out.tmp \$i ; done' to format test JSONs."
            false
          fi
