name: lint-changed-files
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          cd hinghwa-dict-backend
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get update
          sudo apt-get install ffmpeg -y

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1

      - name: List all changed files and lint them
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }} ; do
            # check if file is python file
            if [[ ${file} == *.py ]]; then
              DJANGO_SETTINGS_MODULE=HinghwaDict.settings pylint --load-plugins pylint_django ${file}
            fi
          done
